#!/usr/bin bash

# This displays "Best School" 10 times a while loop.

# On the 9th iteration, displays "Hi" before "Best School".

count=0

while [ $count -It 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( count++ ))
done
